### ISSUE TITLE
Allow certain messages to be reported

### ISSUE THREAD

**Issue by dipterix** [ropensci/targets#1037]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

When code gives warnings or errors in the targets, users can capture the condition signals via `targets::tar_meta`. I wonder if there is a less alert-ish way to print messages. These messages could be very important to let users see, but not warnings.

Currently `targets::tar_message` uses `rlang::inform`. However, that does not save the messages, and cannot be retrieved when running the pipeline non-interactively...

Maybe we can have something for this?  (carefully asking : D

**Comment by wlandau** [comment]
Sorry, I have no plans to build this into `targets` directly. The `_targets/meta/meta` data needs to stay light in order to maintain performance (`targets` already imposes a character limit on warnings and error messages), any change to the metadata would break compatibility with previous versions of `targets`, and  I do not think many people would learn about or use this kind of logging. I suggest a third-party package like [`futile.logger`](https://github.com/zatonovo/futile.logger) using a custom log file and `targets::tar_name()` to get the name of the currently running target.

**Comment by dipterix** [comment]
Gotcha. When I tried

```r
message(structure(list(message = "asdad"), class = c("simpleWarning", "warning", "condition")))
```

I got this error:

<img width="504" alt="image" src="https://user-images.githubusercontent.com/8163576/226698648-4aa050fa-b906-4a95-b486-f254f4a09496.png">
