### ISSUE TITLE
Pins as a possible future target data object

### ISSUE THREAD

**Issue by asadow** [ropensci/targets#1045]
Is there any plan to allow pins as target data objects? My use case would be version control inside OneDrive, with pins potentially living outside the project folder.

**Comment by wlandau** [comment]
You can invoke `pins` in a target if you call `pins::board_register_github()` and then `pins::pin()` inside the command of a target. The idea is very similar to my sketch of a `vetiver` pipeline at https://github.com/ropensci/targets/discussions/1001. I do not plan to create a special storage format for a pin because pins are usually downstream of everything else and do not typically have other targets that depend on them.

**Comment by wlandau** [comment]
That said, you can define your own `pin` format with `targets::tar_format()`.

**Comment by wlandau** [comment]
In fact,  I plan to recommend `tar_format()` going forward for these specialized cases. (I wish I had done this from the beginning for `format = "keras"` and `format = "torch"`).

I am still open to consider new formats if they apply to more general kinds of R objects: for example, for data frames, if something ever supersedes or outperforms `arrow`.
