### ISSUE TITLE
Targets containing `names(object) = paste(names(object), "_x")` do not recognise that the object is the output of a previous target

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/targets#1088]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

Document this bug/feature

## Demo

In this bit of code targets does not see that `rnet_combined` depends on `rnet_commute_list`:

```r
  tar_target(combined_network, {
    
    # ...
    names(rnet_commute_list) = paste0("commute_", names(rnet_commute_list))
    names(rnet_school_list) = paste0("school_", names(rnet_school_list))
    
    rnet_combined = combine_rnets(c(rnet_commute_list,rnet_school_list),
                                  ncores = 20, 
                                  regionalise = 1e5,
                                  add_all = TRUE)
  # ...
    rnet_combined
  }),
```

See that the `rnet_combined` target does not depend on the `rnet_commute_list` object as it should:

![image](https://github.com/ropensci/targets/assets/1825120/e6370da9-eda3-45ef-8c36-d2fda4cd1550)

We fixed this in this commit: https://github.com/nptscot/npt/pull/160/commits/0645362596c88d71e3d0834f74618efecc0fff0b

Heads-up @joeytalbot who reported this issue in https://github.com/nptscot/npt/pull/160 and may have more comments on suggested solutions, not really a feature but one feature could be updates to the docs to describe this behaviour for others changing the column/list names of target objects.

Hope that makes sense!

**Comment by wlandau** [comment]
I agree with the patch you implemented in https://github.com/nptscot/npt/commit/0645362596c88d71e3d0834f74618efecc0fff0b.

Static code analysis happens through the `codetools` package, which is stable and has been around for a long time. However, no static code analysis tool is perfect. Because this specific instance is one of innumerable edge cases, all I can really do is describe how it works in general terms (https://books.ropensci.org/targets/targets.html#dependencies) and recommend that users look at the graph like you have done.
