### ISSUE TITLE
targets DSL proposal

### ISSUE THREAD

**Issue by hadley** [ropensci/targets#1309]
## Prework

* [x] I understand and agree to [help guide](https://books.ropensci.org/targets/help.html).
* [x] I understand and agree to [contributing guide](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.

## Proposal

It occured to me that instead of:

```R
list(
  tar_target(file, "data.csv", format = "file"),
  tar_target(
    data,
    read_csv(file, col_types = cols()) %>%
      filter(!is.na(Ozone))
  ),
  tar_target(
    model,
    lm(Ozone ~ Temp, data) %>%
      coefficients()
  ),
  tar_target(
    plot,
    ggplot(data) +
      geom_point(aes(x = Temp, y = Ozone)) +
      geom_abline(intercept = model[1], slope = model[2]) +
      theme_gray(24)
  )
)
```

You could define a syntax that looks like this:

```R
targets({
  file <- tar_target("data.csv", format = "file")

  data <- tar_target(read_csv(file, col_types = cols()) %>%
      filter(!is.na(Ozone))
  )
  
  model <- tar_target(
    lm(Ozone ~ Temp, data) %>%
      coefficients()
  )
  
  plot <- tar_target(
    ggplot(data) +
      geom_point(aes(x = Temp, y = Ozone)) +
      geom_abline(intercept = model[1], slope = model[2]) +
      theme_gray(24)
  )
})
```

(You'd need to come up with a different function name to avoid ambiguity with the current syntax, but I left it as is because I don't think it fundamentally changes the syntax)

Because the pipe is lazy you could also write this as:

```R
targets({
  file <- tar_target("data.csv", format = "file")

  data <- read_csv(file, col_types = cols()) |> 
    filter(!is.na(Ozone)) |> 
    tar_target()
  
  model <- lm(Ozone ~ Temp, data) |> 
    coefficients() |> 
    tar_target()
  
  plot <- ggplot(data) +
    geom_point(aes(x = Temp, y = Ozone)) +
    geom_abline(intercept = model[1], slope = model[2]) +
    theme_gray(24) |> 
    tar_target()
})
```

(You could possibly consider assuming that any object created with `<-` is automatically wrapped in `tar_target()`, but then you lose the ability to pass other arguments, which is probably not worth it.)

I think this syntax is appealing because it makes it immediately obvious that target name must be a valid symbol name and it creates objects that other targets can depend on.

**Comment by wlandau** [comment]
[`tarchetypes::tar_plan()`](https://docs.ropensci.org/tarchetypes/reference/tar_plan.html) is essentially this DSL, with a few minor differences:

```r
tarchetypes::tar_plan(
  tar_target(file, "data.csv", format = "file"),

  data = read_csv(file, col_types = cols()) |> 
    filter(!is.na(Ozone)) |> 
    tar_target(),
  
  model = lm(Ozone ~ Temp, data) |> 
    coefficients() |> 
    tar_target(),
  
  plot = ggplot(data) +
    geom_point(aes(x = Temp, y = Ozone)) +
    geom_abline(intercept = model[1], slope = model[2]) +
    theme_gray(24) |> 
    tar_target()
)
```

Internally, `tar_plan()` runs the named expressions through `tar_target()` and leaves the unnamed expressions alone. That way, users can mix and match the `name = command` syntax with ordinary syntax.

Rather than trying to detect `tar_target()` with metaprogramming, I chose naming as the mechanism to distinguish between the two types of syntax. The reason is that the right-hand side is not always a call to `tar_target()` or `targets::tar_target()`: it could be 
[`tar_map()`](https://docs.ropensci.org/tarchetypes/reference/tar_map.html), [`tar_combine()`](https://docs.ropensci.org/tarchetypes/reference/tar_combine.html), or a [target factory](https://wlandau.github.io/targetopia/contributing.html#target-factories) such as [`tar_quarto()`](https://docs.ropensci.org/tarchetypes/reference/tar_quarto.html), [`tar_group_by()`](https://docs.ropensci.org/tarchetypes/reference/tar_group_by.html), or [`tar_stan_mcmc()`](https://docs.ropensci.org/stantargets/articles/introduction.html).

**Comment by hadley** [comment]
You wouldn't need any metaprogramming; you could just provide an alternative definition for `<-` in the environment in which it is applied.

**Comment by wlandau** [comment]
Ah, I missed the empty `tar_target()` call at the end of each pipe chain in your example, which resolves my original main concern. I think we can assume each target factory begins with a `name` argument, so your proposed DSL could work well for simple non-[static-branching](https://books.ropensci.org/targets/static.html) cases, and it could be a nice addition to [this list of one](https://docs.ropensci.org/tarchetypes/reference/index.html#domain-specific-languages-for-pipeline-construction) alongside `tar_plan()`. I wonder what we would name it.

**Comment by wlandau** [comment]
> IMO it's a superior user experience to `list()`

Yeah, it will be nice to have syntax which allows `<-` and is not comma-separated.

**Comment by wlandau** [comment]
> Because the pipe is lazy you could also write this as:

Now that I am starting to implement this, I do enjoy how `quote(x |> f())` evaluates to `f(x)`!

**Comment by wlandau** [comment]
The DSL is now implemented as `tarchetypes::tar_assign()` (c.f. https://github.com/ropensci/tarchetypes/pull/187). Happy to revise as appropriate. Thanks for the suggestion!

**Comment by hadley** [comment]
Thanks for implementing it!

**Comment by ginolhac** [comment]
amazing, it boils down to [less than 10 lines](https://github.com/ropensci/tarchetypes/pull/187/files). Show how well `{targets}` internal were well thought in the first place.

**Comment by wlandau** [comment]
> Can we simplify it further to eliminate those tar_target() repetitions in such circumstances.

I agree it's worth thinking about simplifying `tar_assign()` to just pure `name = command`  syntax. Right now you would write a pipeline like this:

```r
tar_assign({
  file <- tar_target("data.csv", format = "file")
  
  data <- read_csv(file, col_types = cols()) |>
    filter(!is.na(Ozone)) |>
    tar_target()
  
  model = lm(Ozone ~ Temp, data) |>
    coefficients() |>
    tar_target()
  
  plot <- {
    ggplot(data) +
      geom_point(aes(x = Temp, y = Ozone)) +
      geom_abline(intercept = model[1], slope = model[2]) +
      theme_gray(24)
  } |>
    tar_target()
})
```

If simplified, you would write it like this:

```r
list(
  tar_target(file, "data.csv", format = "file")
  tar_assign({
    data <- read_csv(file, col_types = cols()) |>
      filter(!is.na(Ozone))
    
    model = lm(Ozone ~ Temp, data) |>
      coefficients()
    
    plot <- ggplot(data) +
      geom_point(aes(x = Temp, y = Ozone)) +
      geom_abline(intercept = model[1], slope = model[2]) +
      theme_gray(24)
  })
)
```

The main advantage is, as you say, dropping repeated `tar_target()` calls. So that's nice. The main disadvantage is that fewer pipelines would fit in a single `tar_assign()` call, so you would need an outer `list()` more often.

**Comment by wlandau** [comment]
> The main disadvantage is that fewer pipelines would fit in a single tar_assign() call, so you would need an outer list() more often.

The current version of `tar_assign()` does not entirely avoid outer `list()` calls all common cases, e.g. because `tar_map()` and `tar_eval()` not compatible.

**Comment by psychelzh** [comment]
> The main disadvantage is that fewer pipelines would fit in a single tar_assign() call, so you would need an outer list() more often.

As for me, I think it is good enough for `tar_assign()` to simplify part of the pipeline. 

But for its completeness, we could add an argument to `tar_assign()` so that users add `tar_target()` manually for certain user cases.

**Comment by wlandau** [comment]
> But for its completeness, we could add an argument to tar_assign() so that users add tar_target() manually for certain user cases.

I would prefer to write two different functions because those are two different DSLs. I'm having trouble thinking of good names that would be evocative and distinct enough.

**Comment by psychelzh** [comment]
I am thinking about using `tar_expressions()` or `tar_exprs()` and `tar_exprs_bare()` (for DSLs without `tar_target()`). Because I think the function essentially includes several lines of R expressions. But maybe it is a little too broad meaning.

Another possibility for me is `tar_local()`, mimicking the base `local()` function which also includes several expressions.

**Comment by hadley** [comment]
IMO `tar_assign()` is already pretty minimal, and adding another syntax along the lines proposed doesn't make any specific pipeline that much simpler, but overall complicates the API of targets/tarchetypes.

**Comment by wlandau** [comment]
Yeah, the two assign-like DSLs could be ambiguous.

@psychelzh, you can implement your version of the DSL for yourself in a single line:

```r
tar_assign2 <- function(expr) {
  purrr::map(match.call()$expr[-1L], \(x) do.call(tar_target, as.list(x)[-1L]))
}
```

Example:

```r
pipeline <- tar_assign2({
  data <- read_csv(file, col_types = cols()) |>
    filter(!is.na(Ozone))
  
  model = lm(Ozone ~ Temp, data) |>
    coefficients()
  
  plot <- ggplot(data) +
    geom_point(aes(x = Temp, y = Ozone)) +
    geom_abline(intercept = model[1], slope = model[2]) +
    theme_gray(24)
})
```
