### ISSUE TITLE
Option to expand pattern nodes into individual targets in tar_watch() shiny UI

### ISSUE THREAD

**Issue by alexpghayes** [ropensci/targets#358]
I think this could be helpful for users who are just learning how to use branching but aren't entirely comfortable with the `pattern` argument behaviour just yet.

I would implement this as a checkbox option that defaults to the current behavior, possibly labelled with a warning about overplotting.

**Comment by wlandau** [comment]
This would have to be done in `tar_visnetwork()` and its internals, and it is a lot harder than it sounds because the names and relationships among dynamic branches change as the workflow progresses, and not all that gets immediately stored in the metadata for efficiency reasons. I see your point about teaching people dynamic branching, but I do not feel it would be worth the tech debt. To see branch progress in a table, you can select "branches" instead of "graph" in the upper left.
