### ISSUE TITLE
tar_target/tar_option_set error argument

### ISSUE THREAD

**Issue by mattwarkentin** [ropensci/targets#405]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [ ] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot. A reproducible example is:
    * [ ] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [ ] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [ ] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Description

Hey @wlandau,

I think the functions `tar_target()` and `tar_option_set()` are missing documentation for `error = "workspace"`. Right now the documentation makes it seem like the only options are `"stop"` and `"continue"`. I vaguely recall this used to be documented but seems to be absent now.

> Character of length 1, what to do if the target runs into an error. If "stop", the whole pipeline stops and throws an error. If "continue", the error is recorded, but the pipeline keeps going.

While I'm thinking about it, should `error = "workspace"` even be an option? Shouldn't a user have the option to save a workspace regardless of whether the pipeline stops or continues when an error is thrown? In other words, I would think `error` should only be able to take the values `"stop"` or `"continue"`, and in either case, if the failed target is named in `workspaces = "..."`, then the workspace is saved. Thoughts? It's late and I'm tired, so maybe this won't make sense when I look at it again in the morning.

**Comment by wlandau** [comment]
Thanks, that's a piece of documentation I forgot to update. Fixed now.

`error = "workspace"` saves just the most useful workspace files in most situations. If we keep going and keep saving workspaces, the files in the data store might get out of hand. This would have been an issue in earlier versions of `targets` when workspace files were deep copies of data, but I still would like to avoid situations like https://github.com/ropensci/drake/issues/154 which were a huge problem because of how `drake`'s storage system was designed. And this problem is combined with the fact that we do not always know in advance which specific targets are going to error. That matters in huge simulation studies with dynamic branching, where it is hard to isolate which branches fail.
