### ISSUE TITLE
Option to set number of clustermq workers

### ISSUE THREAD

**Issue by pat-s** [ropensci/targets#427]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

According to [the targets docs on running clustermq](https://books.ropensci.org/targets/hpc.html#clustermq-locally) one needs to set the amount of workers in every call to `tar_make_clustermq()`.

Previously in {drake} this could be set in `drake_config()`. 
It would be great if this could be supported via `tar_option_set()` or similar.

Please excuse in case this is already possible and I overlooked it 🙏

**Comment by wlandau** [comment]
I would actually prefer not to add a `tar_option_set()` setting for this. Since `tar_make_clsutermq()` already has a `workers` argument, the duplication may cause ambiguity. Also, the settings list is already quite large, and a flexible precedent could let things get out of hand. (`drake_config()` has far too many arguments, many of them deprecated, which is a lot of tech debt.)
