### ISSUE TITLE
tar_config_set()

### ISSUE THREAD

**Issue by yyzeng** [ropensci/targets#616]
I use [targets markdown](https://books.ropensci.org/targets/markdown.html) with several rmarkdown files in a project. I just want one rmarkdown's targets seperated from others' rmarkdown (so as to using `tar_prune()` in the last r chunk to remove targets that are no longer part of the pipeline). After some trial, I  use:  

```
tar_config_set(
  # config = "_targets_01.yaml", # don't work!
  store  = "_targets_01"
)
```
I found the codes almost work for my purpose! But the `config = "_targets_01.yaml"` just does't work (**silently**) - It means I can't set another config yaml file except the default "_targets.yaml" (but I might had thought I had set it). According `tar_config_set()`\'s help, I can set `config = "another_yaml_file"`, then what's wrong?

**Comment by wlandau** [comment]
tar_config_set() stores config info in the yaml file specified in the config argument. It does not persistently set a default yaml file. One workaround is to set the knitr root.dir chunk option to a different path for each R Markdown document. You can use that to manage different yaml files or instead of using yaml files at all.
