### ISSUE TITLE
tar_config_set() stores config info in the yaml file specified in the config argument. It does not persistently set a default yaml file. One workaround is to set the knitr root.dir chunk option to a different path for each R Markdown document. You can use that to manage different yaml files or instead of using yaml files at all.

### ISSUE THREAD

**Issue by yyzeng** [ropensci/targets#618]
tar_config_set() stores config info in the yaml file specified in the config argument. It does not persistently set a default yaml file. One workaround is to set the knitr root.dir chunk option to a different path for each R Markdown document. You can use that to manage different yaml files or instead of using yaml files at all.

_Originally posted by @wlandau in https://github.com/ropensci/targets/issues/616#issuecomment-908866429_

Let me clarify myself. After I use the aboved-mentioned `tar_config_set()`, the "_targets_01.yaml" is present, but configure `store  = "_targets_01"` doesn't work. Storing directories "meta" and "objects" are **still** under "_targets/" (but the "_targets_01/"). 
If I comment out `config = "_targets_01.yaml"`, it comes to work now (but with the default "_targets.yaml"). 

Really a puzzle.

**Comment by wlandau** [comment]
tar_config_set() only modifies the yaml file you choose. When you call tar_make(), targets still looks for a file called _targets.yaml in the current working directory. The purpose of _targets.yaml is to set default values for arguments to tar_make() etc. for the project in the current working directory. Multiple pipelines for multiple reports in the same directory can be managed through the root.dir or tar_script chunk options and/or explicitly setting the store and script arguments of tar_make() etc.

**Comment by yyzeng** [comment]
Good advice! TKS!

**Comment by wlandau** [comment]
A few bits of follow-up:

* To recap, the `config` argument specifies which YAML configuration file that `tar_config_get()` reads from or `tar_config_set()` writes to in a single function call. It does not globally change which configuration file is used in subsequent function calls. To change the default in subsequent function calls (for the given R session) we would need #622.
* In recent commits, I put that explanation in the help files of `tar_config_set()` and `tar_config_get()` to make this clearer.
* In the future, please reply to the original issue or discussion thread (in this case, #616) even if the issue is closed. If you open a new issue to reply, it gets confusing because the discussion is in multiple places.
* For user experience topics like this one, I would prefer to use GitHub Discussions: https://github.com/ropensci/targets/discussions.

**Comment by wlandau** [comment]
Thought about it more and also implemented #623 and #628. Details:  https://books.ropensci.org/targets/projects.html#multiple-projects
