### ISSUE TITLE
Revert use_targets to set up a standard _targets.R file

### ISSUE THREAD

**Issue by noamross** [ropensci/targets#639]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

targets-markdown is an interesting development, but many of us will continue to use a `_targets.R` based workflow and `use_targets()` was helpful for setting up such projects.  I suggest reverting `use_targets()` to its original approach and  adding `use_targets_rmd()` for the current functionality.

**Comment by wlandau** [comment]
Did `use_targets()` previously write `_targets.R`? Looking back at the news and old CRAN releases, I am having trouble finding a past version that does. Versions since 0.5.0 (that one is GitHub only) seem to to write `_targets.Rmd` instead.

You make a good point, but the change would be non-back-compatible at this point. Also, `tar_script()` already writes an example `_targets.R` file, which is a small part of a serious `targets` project with lots of files. The nice thing about Target Markdown is that you can put all your code in a single R Markdown document and then `targets` creates all those `R/` scripts for you. I feel this single-file approach is more compatible with `usethis`-like features.

**Comment by wlandau** [comment]
I decided to take your original advice. Working on moving the current `use_targets()` to `use_targets_rmd()` and creating a more convenient version of `use_targets()`.

**Comment by alexpghayes** [comment]
I think this a great change, thanks!
